# fly.toml app configuration file generated for example-opentelemetry-collector-http-check on 2024-01-05T21:14:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "example-opentelemetry-collector-http-check"
primary_region = "syd"

[build]

[deploy]
strategy = "immediate"

[env]
GOMEMLIMIT = "207MiB" # 256MB in MiB (256 * 1024 * 1024) * 0.8
GOMAXPROCS = "1"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[metrics]
port = 9091
path = "/metrics"

[checks]
[checks.opentelemetry_collector_http]
grace_period = "10s"
interval = "10s"
method = "get"
path = "/health/status"
port = 13133
timeout = "5s"
type = "http"
