receivers:
  httpcheck:
    targets:
      - endpoint: https://kallan.dev:443
        method: GET
    collection_interval: 10s

processors:
  batch:

exporters:
  debug:

service:
  extensions: []
  pipelines:
    metrics:
      receivers:
        - httpcheck
      processors:
        - batch
      exporters:
        - debug
