receivers:
  httpcheck:
    targets:
      - endpoint: https://kallan.dev:443
        method: GET
    collection_interval: 60s

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: [":8888"]

processors:
  batch:

exporters:
  prometheus:
    endpoint: ":9091"

extensions:
  health_check:
    path: "/health/status"

service:
  extensions:
    - health_check

  pipelines:
    metrics:
      receivers:
        - httpcheck
        - prometheus
      processors:
        - batch
      exporters:
        - prometheus

  telemetry:
    metrics:
      address: ":8888"
