receivers:
  httpcheck:
    targets:
      - endpoint: https://kallan.dev:443
        method: GET
    collection_interval: 10s

processors:
  batch:

exporters:
  debug:
    # verbosity: detailed

  prometheus:
    endpoint: ":9091"
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    path: "/health/status"

service:
  extensions:
    - health_check
  pipelines:
    metrics:
      receivers:
        - httpcheck
      processors:
        - batch
      exporters:
        - debug
        - prometheus

  telemetry:
    metrics:
      address: ":8888"
