receivers:
  httpcheck:
    targets:
      - endpoint: https://kallan.dev:443
        method: GET

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: [":8888"]

processors:
  batch:

exporters:
  debug:
    # verbosity: detailed

  prometheus:
    endpoint: ":9091"
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    path: "/health/status"

service:
  extensions:
    - health_check

  pipelines:
    metrics:
      receivers:
        - httpcheck
        - prometheus
      processors:
        - batch
      exporters:
        - prometheus

  telemetry:
    metrics:
      address: ":8888"
